### PR TITLE
[TRANSLATION] review & improve translation

### PR DESCRIPTION
**Pull request by kernelbin**

### CODE REVIEW

**Review by GNAQ — CHANGES_REQUESTED** [review]
To be fixed：

- [x] `窗口` -> `window`

- [ ] `选项卡 / 标签` -> `tab`

**Comment by kernelbin** [comment]
> To be fixed：
> 
> * [x]  `窗口` -> `window`
> * [x]  `选项卡 / 标签` -> `tab`

I still kept several "window" and "tab" translated to Chinese because I think under that context it's better to translate it.
but I'm not sure about that, could you please take a look at it?

**Review by GNAQ — CHANGES_REQUESTED** [review]
我认为 `320` 行的「窗口」最好换为 window，其余则保留翻译。

**Comment by kernelbin** [comment]
> 我认为 `320` 行的「窗口」最好换为 window，其余则保留翻译。

我不清楚320行指代的window的具体含义，那么就按你的意见更换吧

**Review by GNAQ — APPROVED** [review]
OK to merge

**Pull request merged**
